# Generated by Django 4.1.3 on 2022-12-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='beat_category',
            field=models.CharField(choices=[('R&B', 'R&B'), ('D&B', 'Drum and Bass'), ('Trap', 'Trap')], default='R&B', max_length=12),
        ),
        migrations.AlterField(
            model_name='beat',
            name='beat_file',
            field=models.FileField(upload_to='musicfile/2022-12-01'),
        ),
    ]
