# Generated by Django 4.1.3 on 2022-12-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0004_alter_beat_beat_category_alter_beat_beat_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='featured_beat',
            field=models.BooleanField(default=False),
        ),
    ]
