# Generated by Django 4.1.3 on 2022-12-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0005_beat_featured_beat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_img', models.ImageField(upload_to='eventImg/2022-12-02')),
                ('event_name', models.CharField(max_length=100)),
                ('event_place', models.CharField(max_length=100)),
                ('event_status', models.CharField(blank=True, choices=[('', ''), ('soon', 'Comming Soon'), ('sold', 'Sold Out')], default='', max_length=30, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='beat',
            name='beat_file',
            field=models.FileField(upload_to='musicfile/2022-12-02'),
        ),
    ]
